version: '1'

#Service containers
services:
  postgres:
    image: postgres:15.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Welkom12345"
    ports:
      - "5432:5432/tcp"
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
        
  jeager:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

volumes:
  rabbitmq-data: