name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --configuration Release

  build_submodules:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build submodules
        run: |
          git submodule foreach --recursive 'git checkout main && git pull && dotnet build --configuration Release'
