name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --configuration Release
        
  build_submodules:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build submodules
        run: |
          cd Forfeit15-patch-notes
          git checkout main
          git pull
