name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Add custom package source
        run: dotnet nuget add source https://nuget.pkg.github.com/DamianHoogsteder/index.json --name github --username DamianHoogsteder --password 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
      - name: Build submodules
        run: |
          git submodule foreach --recursive 'git checkout main && git pull && dotnet build --configuration Release'
          
  test_submodules:
    runs-on: ubuntu-latest
    needs: build_submodules
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Add custom package source
        run: dotnet nuget add source https://nuget.pkg.github.com/DamianHoogsteder/index.json --name github --username DamianHoogsteder --password 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
      - name: Build submodules
        run: |
          git submodule foreach --recursive 'git checkout main && git pull && dotnet test --configuration Release'
          
